//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album_Gallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album_Gallery()
        {
            this.Album_Gallery_Images = new HashSet<Album_Gallery_Images>();
        }
    
        public int Galleryid { get; set; }
        public string AlbumName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> GalleryDate { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string AlbumType { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album_Gallery_Images> Album_Gallery_Images { get; set; }
    }
}
