//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_Gallery
    {
        public int Galleryid { get; set; }
        public string AlbumName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> GalleryDate { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string AlbumType { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int AlbumId { get; set; }
    }
}
