//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custome_Templates
    {
        public int id { get; set; }
        public string Heading { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Images { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
