//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Memories_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_Memories_Info()
        {
            this.db_Memories_images = new HashSet<db_Memories_images>();
        }
    
        public int MemoriesId { get; set; }
        public Nullable<long> Userid { get; set; }
        public string Heading { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> MemoryDate { get; set; }
        public string VisibleTo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool Status { get; set; }
        public Nullable<int> VisibleBatchfrom { get; set; }
        public Nullable<int> VisibleBatchTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Memories_images> db_Memories_images { get; set; }
    }
}
