//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Def_Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Def_Events()
        {
            this.Event_Faqs = new HashSet<Event_Faqs>();
            this.Event_Gallery = new HashSet<Event_Gallery>();
            this.Event_TicketTypes = new HashSet<Event_TicketTypes>();
            this.Event_UserSelections = new HashSet<Event_UserSelections>();
            this.Event_AttendingStatus = new HashSet<Event_AttendingStatus>();
        }
    
        public int EventId { get; set; }
        public string EventName { get; set; }
        public string BannerImage { get; set; }
        public Nullable<System.DateTime> EventStartdate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string MobileNumber { get; set; }
        public string Landline { get; set; }
        public string Email { get; set; }
        public string EventVenue { get; set; }
        public string EventDescription { get; set; }
        public Nullable<int> VisitorsCount { get; set; }
        public Nullable<int> TotalNoOfTickets { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool Status { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_Faqs> Event_Faqs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_Gallery> Event_Gallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_TicketTypes> Event_TicketTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_UserSelections> Event_UserSelections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_AttendingStatus> Event_AttendingStatus { get; set; }
    }
}
