//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor_Details
    {
        public long ID { get; set; }
        public Nullable<long> Donation_ID { get; set; }
        public Nullable<long> Donor_ID { get; set; }
        public Nullable<decimal> Donation_Amount { get; set; }
        public string Donation_Status { get; set; }
        public Nullable<long> Transaction_ID { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Donation_Details Donation_Details { get; set; }
        public virtual Transaction_Details Transaction_Details { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
