//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalDetail
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string CollegeName { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> Batch { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
