//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_UserPayments
    {
        public int PaymentId { get; set; }
        public long UserId { get; set; }
        public int UserSelectionId { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string PaymentStatus { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
    
        public virtual Event_UserSelections Event_UserSelections { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
