//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events_UserBookings
    {
        public int BookId { get; set; }
        public Nullable<int> TicketTypeId { get; set; }
        public int EventSelectionId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> TotalTickets { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Event_TicketTypes Event_TicketTypes { get; set; }
        public virtual Event_UserSelections Event_UserSelections { get; set; }
    }
}
