//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyWorkInfo
    {
        public long Id { get; set; }
        public long FacultyUserId { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> WorkingFrom { get; set; }
        public Nullable<int> WorkingTo { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
