//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction_Details()
        {
            this.Donor_Details = new HashSet<Donor_Details>();
        }
    
        public long Transaction_ID { get; set; }
        public string Txn_Ref_No { get; set; }
        public string PG_Txn_ID { get; set; }
        public string Txn_Status { get; set; }
        public string Txn_Message { get; set; }
        public Nullable<decimal> Txn_Amount { get; set; }
        public Nullable<decimal> Service_Tax { get; set; }
        public string Currency_Code { get; set; }
        public string Comments { get; set; }
        public string Payment_Mode { get; set; }
        public string Card_Info { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donor_Details> Donor_Details { get; set; }
    }
}
