//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserPost()
        {
            this.UserPost_Files = new HashSet<UserPost_Files>();
            this.UserPost_Images = new HashSet<UserPost_Images>();
            this.UserPost_Likes = new HashSet<UserPost_Likes>();
            this.UserPosts_Visisble = new HashSet<UserPosts_Visisble>();
        }
    
        public int PostId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string UserMessage { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Unlike { get; set; }
        public string ViewBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual EventCategory EventCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPost_Files> UserPost_Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPost_Images> UserPost_Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPost_Likes> UserPost_Likes { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPosts_Visisble> UserPosts_Visisble { get; set; }
    }
}
