//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPosting_Jobs
    {
        public int Jobid { get; set; }
        public Nullable<long> Userid { get; set; }
        public string JobTitle { get; set; }
        public string ComanyName { get; set; }
        public string ComanyUrl { get; set; }
        public string ExperienceRequired { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
        public string Skills { get; set; }
        public string Salary { get; set; }
        public Nullable<int> FunctionalId { get; set; }
        public string Role { get; set; }
        public string Qualification { get; set; }
        public string Description { get; set; }
        public string Filepath { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Job_FunctionalArea Job_FunctionalArea { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
