//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.EducationalDetails = new HashSet<EducationalDetail>();
            this.FacultyWorkInfoes = new HashSet<FacultyWorkInfo>();
            this.ProfessionalDetails = new HashSet<ProfessionalDetail>();
            this.UserPost_Comments = new HashSet<UserPost_Comments>();
            this.UserPost_Likes = new HashSet<UserPost_Likes>();
            this.UserPosts = new HashSet<UserPost>();
            this.Event_UserSelections = new HashSet<Event_UserSelections>();
            this.Event_UserPayments = new HashSet<Event_UserPayments>();
            this.Event_AttendingStatus = new HashSet<Event_AttendingStatus>();
            this.UserPosting_Jobs = new HashSet<UserPosting_Jobs>();
            this.Donor_Details = new HashSet<Donor_Details>();
        }
    
        public long Id { get; set; }
        public string AspnetUsersId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public int HomeCityId { get; set; }
        public string HomeVillegeOrAreaName { get; set; }
        public int LivesInCityId { get; set; }
        public Nullable<int> LivesInVillegeOrAreaName { get; set; }
        public Nullable<int> SalutationId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ProfilePicture { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public Nullable<int> ProfileInfoPercentage { get; set; }
        public string AlternateEmailId { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public string PhoneNumber { get; set; }
        public string HomePhoneNumber { get; set; }
        public string PortalPassword { get; set; }
        public string PermanentAddress { get; set; }
        public string PresentCity { get; set; }
        public string PermanentCity { get; set; }
        public Nullable<int> PresentDistid { get; set; }
        public Nullable<int> PermanentDistid { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationalDetail> EducationalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacultyWorkInfo> FacultyWorkInfoes { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessionalDetail> ProfessionalDetails { get; set; }
        public virtual Salutation Salutation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPost_Comments> UserPost_Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPost_Likes> UserPost_Likes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPost> UserPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_UserSelections> Event_UserSelections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_UserPayments> Event_UserPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_AttendingStatus> Event_AttendingStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPosting_Jobs> UserPosting_Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donor_Details> Donor_Details { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
    }
}
