//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPost_Likes
    {
        public int LikeId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserPost UserPost { get; set; }
    }
}
