//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumini.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserDetails
    {
        public long UserId { get; set; }
        public string AspnetUsersId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string HomeVillegeOrAreaName { get; set; }
        public string HomeCityName { get; set; }
        public string LivesInCityName { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public Nullable<int> ProfileInfoPercentage { get; set; }
        public string PhoneNumber { get; set; }
        public string AlternateEmailId { get; set; }
        public string HomePhoneNumber { get; set; }
        public string PortalPassword { get; set; }
        public string Salutation { get; set; }
        public string GenderName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Email { get; set; }
        public string LoginName { get; set; }
        public string RoleId { get; set; }
        public string Role { get; set; }
        public string CollegeName { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> Batch { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> WorkingFrom { get; set; }
        public Nullable<int> WorkingTo { get; set; }
        public string CourseCategoryName { get; set; }
        public Nullable<int> Years { get; set; }
        public string ProfilePicture { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
        public string WorkedFrom { get; set; }
        public string WorkedTill { get; set; }
        public string CityName { get; set; }
        public string PasswordHash { get; set; }
    }
}
